# .goreleaser.yml
# Build customization
build:
  binary: malice
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
  # hooks:
  #   post: /bin/sh install/scripts/upx.sh

archive:
  files:
    - contrib/completion/zsh/_malice
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip    
  replacements:
    amd64: amd64
    darwin: macOS
    linux: linux
    windows: win

changelog:
  filters:
    exclude:
    - '^docs:'
    - update README
    - '^update vendor'
    - '^small'
    - updates
    - fixes
  sort: asc

sign:
  artifacts: checksum

brew:
  github:
    owner: maliceio
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/maliceio/malice"
  description: "Open Source Malware Analysis Framework."
  install: |
    bin.install "malice"
    zsh_completion.install "contrib/completion/zsh/_malice"
  test: |
    system "#{bin}/malice --version"

nfpm:
  vendor: MaliceIO
  homepage: https://malice.io/
  maintainer: Blacktop <github.com/blacktop>
  description: Open Source Malware Analysis Framework.
  license: Apache 2.0
  formats:
  - deb
  - rpm
  files:
    "contrib/completion/zsh/_malice": "$HOME/.zsh/completion/_malice"
    "contrib/completion/bash/malice": "/etc/bash_completion.d/malice"
  #   "scripts/etc/init.d/": "/etc/init.d"
  #   "path/**/glob": "/var/foo/glob"
  # config_files:
  #   "tmp/app_generated.conf": "/etc/app.conf"
  #   "conf/*.conf": "/etc/foo/"
